---
- name: Ensure boto and boto3 modules are installed
  pip:
    name: "{{ item }}"
  with_items:
    - boto3
    - botocore

- name: Installing the required repository
  shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -

- name: Install nodejs v14
  apt:
    name: nodejs
    state: latest

